# Generated by Django 6.0.8 on 2026-09-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_quick_switch_pin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="pin_failed_attempts",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="pin_locked_until",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="quick_pin_hash",
        ),
    ]
