# Generated by Django 6.0.8 on 2026-09-11 15:48

import django.db.models.deletion
from django.db import migrations, models


def connect_water_and_beans(apps, schema_editor):
    TableAccountItem = apps.get_model("tables", "TableAccountItem")
    for item in TableAccountItem.objects.select_related("daily_menu").filter(
        daily_menu__isnull=False,
    ).iterator():
        values = {}
        if item.with_water:
            values["water_product_id"] = item.daily_menu.water_product_id
        if item.beans:
            values["beans_product_id"] = item.daily_menu.beans_order_id
        if values:
            TableAccountItem.objects.filter(pk=item.pk).update(**values)


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0018_alter_stockmovement_actor"),
        ("tables", "0016_natural_table_map_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableaccountitem",
            name="beans_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="table_items_as_beans",
                to="menu.product",
            ),
        ),
        migrations.AddField(
            model_name="tableaccountitem",
            name="water_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="table_items_as_water",
                to="menu.product",
            ),
        ),
        migrations.RunPython(connect_water_and_beans, migrations.RunPython.noop),
    ]
