# Generated by Django 6.0.8 on 2026-09-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0021_daily_stock_default_alert_threshold"),
        ("tables", "0017_tableaccountitem_beans_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableaccountitem",
            name="egg_name_snapshot",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="tableaccountitem",
            name="egg_price_snapshot",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="tableaccountitem",
            name="egg_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="table_items_as_egg",
                to="menu.product",
            ),
        ),
    ]
