# Generated by Django 6.0.8 on 2026-09-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0018_tableaccountitem_egg_name_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableaccountitem",
            name="bread",
            field=models.BooleanField(default=False),
        ),
    ]
