# Generated by Django 6.0.8 on 2026-09-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0019_tableaccountitem_bread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableaccount",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Abierta"),
                    ("closed", "Cerrada"),
                    ("transferred", "Transferida a pedido"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
