# Generated by Django 6.0.8 on 2026-09-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0020_alter_tableaccount_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableaccountitem",
            name="is_two_course",
            field=models.BooleanField(default=False),
        ),
    ]
