# Generated by Django 6.0.8 on 2026-10-06 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0021_tableaccountitem_is_two_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableaccount",
            name="split_active",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tableaccount",
            name="split_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tableaccount",
            name="split_mode",
            field=models.BooleanField(default=False, verbose_name="cuentas separadas"),
        ),
        migrations.AddField(
            model_name="tableaccount",
            name="split_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tableaccount",
            name="split_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="split_children",
                to="tables.tableaccount",
            ),
        ),
        migrations.AddField(
            model_name="tableaccountitem",
            name="split_slot",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
