# Generated by Django 6.0.8 on 2026-10-06 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0022_table_split_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tableaccount",
            name="parked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tableaccount",
            name="parked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parked_table_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tableaccount",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Abierta"),
                    ("closed", "Cerrada"),
                    ("transferred", "Transferida a pedido"),
                    ("parked", "Pendiente"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tableactivity",
            name="action",
            field=models.CharField(
                choices=[
                    ("open", "Abrió la mesa"),
                    ("add", "Agregó producto"),
                    ("customize", "Agregó producto modificado"),
                    ("increase", "Aumentó cantidad"),
                    ("decrease", "Disminuyó cantidad"),
                    ("remove", "Eliminó partida"),
                    ("package", "Agregó paquete"),
                    ("package_edit", "Editó paquete"),
                    ("reassign", "Cambió responsable"),
                    ("customer", "Actualizó cliente"),
                    ("close", "Cobró y cerró"),
                    ("park", "Dejó pendiente"),
                    ("resume", "Retomó la cuenta"),
                ],
                max_length=20,
            ),
        ),
    ]
