# Generated by Django 6.0.8 on 2026-09-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print_station", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="cocina", max_length=50, unique=True),
                ),
                ("printer_available", models.BooleanField(default=False)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="printjob",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("printing", "En impresión"),
                    ("printed", "Enviado a impresora"),
                    ("failed", "Error"),
                    ("expired", "Expirado"),
                ],
                db_index=True,
                default="pending",
                max_length=12,
            ),
        ),
    ]
