# Generated by Django 6.0.8 on 2026-09-10 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0013_product_image_framing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailymenu",
            name="chicken_consomme",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "component_type__in": ("chicken_consomme", "variable_first_course")
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="daily_menus_as_chicken_consomme",
                to="menu.product",
            ),
        ),
    ]
