# Generated by Django 6.0.8 on 2026-09-11 08:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0015_distinguish_daily_water"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProductStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("table", "Mesas"),
                            ("pickup", "Recoger"),
                            ("delivery", "Entrega a domicilio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("initial_quantity", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_stocks",
                        to="menu.dailymenu",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_stocks",
                        to="menu.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "existencia diaria",
                "verbose_name_plural": "existencias diarias",
                "ordering": ("date", "product__name", "channel"),
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Usa cantidades negativas para salidas y positivas para devoluciones o entradas."
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("reservation", "Apartado para ticket"),
                            ("release", "Devolución al inventario"),
                            ("consumption", "Consumo confirmado"),
                            ("adjustment", "Ajuste manual"),
                            ("transfer_in", "Entrada por transferencia"),
                            ("transfer_out", "Salida por transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Origen del movimiento, por ejemplo order o table_account.",
                        max_length=30,
                    ),
                ),
                ("reference_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="menu.dailyproductstock",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento de inventario",
                "verbose_name_plural": "movimientos de inventario",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="dailyproductstock",
            constraint=models.UniqueConstraint(
                fields=("date", "product", "channel"),
                name="unique_daily_product_stock_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity", 0), _negated=True),
                name="stock_movement_quantity_nonzero",
            ),
        ),
    ]
