# Generated by Django 6.0.8 on 2026-09-11 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0016_daily_stock_ledger"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyproductstock",
            options={
                "ordering": ("date", "item_kind", "product__name", "channel"),
                "verbose_name": "existencia diaria",
                "verbose_name_plural": "existencias diarias",
            },
        ),
        migrations.RemoveConstraint(
            model_name="dailyproductstock",
            name="unique_daily_product_stock_channel",
        ),
        migrations.AddField(
            model_name="dailyproductstock",
            name="item_kind",
            field=models.CharField(
                choices=[
                    ("product", "Producto"),
                    ("tortillas", "Porción de tortillas"),
                    ("bread", "Bolillo"),
                ],
                default="product",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dailyproductstock",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="daily_stocks",
                to="menu.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyproductstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item_kind", "product")),
                fields=("date", "product", "channel"),
                name="unique_daily_product_stock_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyproductstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item_kind", "product"), _negated=True),
                fields=("date", "item_kind", "channel"),
                name="unique_daily_supply_stock_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyproductstock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("item_kind", "product"), ("product__isnull", False)),
                    models.Q(
                        models.Q(("item_kind", "product"), _negated=True),
                        ("product__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="daily_stock_product_matches_kind",
            ),
        ),
    ]
