# Generated by Django 6.0.8 on 2026-09-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0018_alter_stockmovement_actor"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dailyproductstock",
            name="unique_daily_product_stock_channel",
        ),
        migrations.AddField(
            model_name="dailyproductstock",
            name="chicken_piece",
            field=models.CharField(
                blank=True,
                choices=[("leg", "Pierna"), ("thigh", "Muslo")],
                help_text="Solo se usa para separar pierna y muslo del guisado de pollo.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyproductstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item_kind", "product")),
                fields=("date", "product", "channel", "chicken_piece"),
                name="unique_daily_product_stock_channel",
            ),
        ),
    ]
