# Generated by Django 6.0.8 on 2026-09-11 17:51

import django.utils.timezone
from django.db import migrations, models


def merge_order_channels(apps, schema_editor):
    Stock = apps.get_model("menu", "DailyProductStock")
    Movement = apps.get_model("menu", "StockMovement")
    pickup_rows = list(Stock.objects.filter(channel="pickup").order_by("pk"))
    for pickup in pickup_rows:
        delivery = Stock.objects.filter(
            channel="delivery", date=pickup.date, item_kind=pickup.item_kind,
            product_id=pickup.product_id, chicken_piece=pickup.chicken_piece,
        ).first()
        if delivery:
            pickup.initial_quantity += delivery.initial_quantity
            Movement.objects.filter(stock_id=delivery.pk).update(stock_id=pickup.pk)
            delivery.delete()
        pickup.channel = "orders"
        pickup.save(update_fields=("channel", "initial_quantity"))
    Stock.objects.filter(channel="delivery").update(channel="orders")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        (
            "menu",
            "0019_remove_dailyproductstock_unique_daily_product_stock_channel_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dailyproductstock",
            name="unique_daily_supply_stock_channel",
        ),
        migrations.RemoveConstraint(
            model_name="dailyproductstock",
            name="unique_daily_product_stock_channel",
        ),
        migrations.AddField(
            model_name="dailyproductstock",
            name="stock_type",
            field=models.CharField(
                choices=[("daily", "Menú diario"), ("fixed", "Menú fijo")],
                db_index=True,
                default="daily",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dailyproductstock",
            name="is_tracked",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="dailyproductstock",
            name="channel",
            field=models.CharField(
                choices=[
                    ("table", "Mesas"),
                    ("orders", "Pedidos"),
                    ("shared", "Todos los canales"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dailyproductstock",
            name="date",
            field=models.DateField(
                blank=True,
                db_index=True,
                default=django.utils.timezone.localdate,
                null=True,
            ),
        ),
        migrations.RunPython(merge_order_channels, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="dailyproductstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item_kind", "product"), ("stock_type", "daily")),
                fields=("date", "product", "channel", "chicken_piece"),
                name="unique_daily_product_stock_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyproductstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("item_kind", "product"), _negated=True),
                    ("stock_type", "daily"),
                ),
                fields=("date", "item_kind", "channel"),
                name="unique_daily_supply_stock_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyproductstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item_kind", "product"), ("stock_type", "fixed")),
                fields=("product",),
                name="unique_fixed_product_stock",
            ),
        ),
    ]
