# Generated by Django 6.0.8 on 2026-09-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0021_daily_stock_default_alert_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="uses_bread_stock",
            field=models.BooleanField(
                default=False,
                help_text="Descuenta una unidad del conteo diario de bolillos por cada unidad vendida.",
            ),
        ),
    ]
