# Generated by Django 6.0.8 on 2026-10-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0023_inventoryauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="show_to_customers",
            field=models.BooleanField(
                default=True, verbose_name="visible para clientes"
            ),
        ),
    ]
