# Generated by Django 6.0.8 on 2026-10-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0026_daily_menu_stews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailymenu",
            name="beef_stew",
        ),
        migrations.RemoveField(
            model_name="dailymenu",
            name="chicken_stew",
        ),
        migrations.RemoveField(
            model_name="dailymenu",
            name="varied_stew",
        ),
    ]
