# Generated by Django 6.0.8 on 2026-10-07 17:15

from django.db import migrations, models

# Productos del menú del QR acordados con el dueño (IDs de producción, 2026-10-07):
# Desayunos (sin "Huevos revuelto/estrellado desayuno"), Plancha (sin enchiladas de mole,
# pico de gallo, totopos, extras y sope sólo tortilla), Bebidas calientes, Bebidas frías
# (sin jugo de toronja; el "Agua del día" se agrega aparte en la página) y Postres (sin
# dulce típico). Comida corrida y Comida por orden no entran.
QR_MENU_PRODUCT_IDS = [
    # Desayunos
    1, 37, 6, 58, 59, 62, 67, 68, 69, 70, 71, 72, 73, 93, 94,
    # Plancha
    10, 36, 35, 82, 34, 49, 83, 48, 84, 33, 4, 76, 78, 79, 80, 75, 74, 77, 81, 25, 26, 85, 86,
    87, 27, 2, 88, 89, 90, 91, 63, 92, 95, 150, 153, 155, 161, 184, 185, 196, 201, 203, 204, 205,
    # Bebidas calientes
    16, 29, 28, 54, 57, 96, 97, 98, 99, 100,
    # Bebidas frías
    23, 61, 120, 147,
    # Postres
    50, 51, 52, 53, 101, 102, 103, 104, 105, 119, 130, 131, 15, 159, 169, 218,
]


def mark_qr_menu_products(apps, schema_editor):
    Product = apps.get_model("menu", "Product")
    Product.objects.filter(pk__in=QR_MENU_PRODUCT_IDS).update(show_in_qr_menu=True)


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0027_remove_fixed_stews"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="show_in_qr_menu",
            field=models.BooleanField(default=False, verbose_name="mostrar en menú QR"),
        ),
        migrations.RunPython(mark_qr_menu_products, migrations.RunPython.noop),
    ]
