# Generated by Django 6.0.8 on 2026-10-09 16:50

from django.db import migrations, models


OLD_NAME = "Comida corrida"
NEW_NAME = "Comida mexicana"


def rename(apps, old, new):
    # Sólo se renombra lo que conserva el nombre exacto (no pisa cambios hechos a mano).
    apps.get_model("menu", "Category").objects.filter(name=old).update(name=new)
    apps.get_model("menu", "MealPackage").objects.filter(package_type="running", name=old).update(name=new)


def forwards(apps, schema_editor):
    rename(apps, OLD_NAME, NEW_NAME)


def backwards(apps, schema_editor):
    rename(apps, NEW_NAME, OLD_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0028_product_show_in_qr_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="show_table_packages",
            field=models.BooleanField(
                default=False,
                help_text="Actívalo en la categoría que debe abrir Comida mexicana y ejecutiva.",
                verbose_name="mostrar paquetes de mesa al elegirla",
            ),
        ),
        migrations.AlterField(
            model_name="mealpackage",
            name="package_type",
            field=models.CharField(
                choices=[
                    ("running", "Comida mexicana"),
                    ("executive", "Comida ejecutiva"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
