# Generated by Django 6.0.8 on 2026-09-11 15:43

import django.db.models.deletion
from django.db import migrations, models


def connect_items_to_original_daily_menu(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    DailyMenu = apps.get_model("menu", "DailyMenu")
    menu_fields = (
        "water_product_id", "chicken_consomme_id", "variable_first_course_id",
        "second_course_one_id", "second_course_two_id", "chicken_stew_id",
        "beef_stew_id", "varied_stew_id", "beans_order_id",
    )
    menus = {menu.date: menu for menu in DailyMenu.objects.all()}
    for item in OrderItem.objects.select_related("order").all().iterator():
        daily_menu = menus.get(item.order.operating_date)
        if not daily_menu:
            continue
        daily_ids = {getattr(daily_menu, field) for field in menu_fields}
        if item.item_type == "package" or item.is_package_candidate or item.product_id in daily_ids:
            values = {"daily_menu_id": daily_menu.pk}
            if item.with_water:
                values["water_product_id"] = daily_menu.water_product_id
            if item.beans:
                values["beans_product_id"] = daily_menu.beans_order_id
            OrderItem.objects.filter(pk=item.pk).update(**values)


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0018_alter_stockmovement_actor"),
        ("orders", "0022_orderitem_bread"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="daily_menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="menu.dailymenu",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="water_product",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order_items_as_water", to="menu.product"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="beans_product",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order_items_as_beans", to="menu.product"),
        ),
        migrations.RunPython(
            connect_items_to_original_daily_menu, migrations.RunPython.noop,
        ),
    ]
