# Generated by Django 6.0.8 on 2026-09-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_customer_credit_balance_order_credit_applied_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercreditmovement",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Efectivo"),
                    ("card", "Terminal"),
                    ("transfer", "Transferencia"),
                    ("credit", "Saldo a favor"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customerdebtmovement",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Efectivo"),
                    ("card", "Terminal"),
                    ("transfer", "Transferencia"),
                    ("credit", "Saldo a favor"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Efectivo"),
                    ("card", "Terminal"),
                    ("transfer", "Transferencia"),
                    ("credit", "Saldo a favor"),
                ],
                max_length=20,
            ),
        ),
    ]
