# Generated by Django 6.0.8 on 2026-09-28 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0029_cashregistercut_cashregisterexpense"),
        ("tables", "0020_alter_tableaccount_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transferred_from_table",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferred_to_order",
                to="tables.tableaccount",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="transferred_to_table",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferred_from_order",
                to="tables.tableaccount",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Capturando"),
                    ("pending_confirmation", "Pendiente de confirmar"),
                    ("confirmed", "Confirmado"),
                    ("scheduled", "Programado"),
                    ("preparing", "En preparación"),
                    ("ready", "Listo"),
                    ("out_for_delivery", "En reparto"),
                    ("picked_up", "Recogido"),
                    ("delivered", "Entregado"),
                    ("canceled", "Cancelado"),
                    ("transferred", "Transferido a mesa"),
                ],
                default="pending_confirmation",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("draft", "Capturando"),
                    ("pending_confirmation", "Pendiente de confirmar"),
                    ("confirmed", "Confirmado"),
                    ("scheduled", "Programado"),
                    ("preparing", "En preparación"),
                    ("ready", "Listo"),
                    ("out_for_delivery", "En reparto"),
                    ("picked_up", "Recogido"),
                    ("delivered", "Entregado"),
                    ("canceled", "Cancelado"),
                    ("transferred", "Transferido a mesa"),
                ],
                max_length=30,
            ),
        ),
    ]
