# Generated by Django 6.0.8 on 2026-09-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0032_terminalmovement_display_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_two_course",
            field=models.BooleanField(default=False),
        ),
    ]
