# Generated by Django 6.0.8 on 2026-10-01 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0033_orderitem_is_two_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerdebtmovement",
            name="credit_movement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="debt_movement",
                to="orders.customercreditmovement",
            ),
        ),
        migrations.AlterField(
            model_name="customerdebtmovement",
            name="action",
            field=models.CharField(
                choices=[
                    ("payment", "Abono"),
                    ("credit", "Pagado con saldo a favor"),
                    ("forgive", "Condonación"),
                    ("reopen", "Reapertura"),
                ],
                max_length=15,
            ),
        ),
    ]
