# Generated by Django 6.0.8 on 2026-10-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0034_customer_debt_paid_with_credit"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryStreet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="calle")),
                (
                    "number_from",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="desde el número"
                    ),
                ),
                (
                    "number_to",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="hasta el número"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
            ],
            options={
                "verbose_name": "calle de reparto",
                "verbose_name_plural": "calles de reparto",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="order",
            name="address_from_agenda",
            field=models.BooleanField(
                default=False, verbose_name="usar domicilio registrado"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="outside_delivery_zone",
            field=models.BooleanField(default=False, verbose_name="fuera de zona"),
        ),
    ]
