# Generated by Django 6.0.8 on 2026-10-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0037_order_web_customer_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_key", ""), _negated=True),
                fields=("phone_key",),
                name="unique_customer_phone_key",
                violation_error_message="Este celular ya pertenece a otro cliente.",
            ),
        ),
    ]
