# Generated by Django 6.0.8 on 2026-10-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0038_customer_unique_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercreditmovement",
            name="action",
            field=models.CharField(
                choices=[
                    ("deposit", "Depósito"),
                    ("redemption", "Aplicado a pedido"),
                    ("refund", "Devolución"),
                    ("order_adjust", "Regresado por ajuste del pedido"),
                ],
                max_length=15,
            ),
        ),
    ]
